name: Main Pipeline
on:
 workflow_dispatch:
 push:
   branches:
     - "main"

jobs:
  Unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Lanzar test unitarios
        run: |
          set -ev
          cd modern-web-app
          npm ci
          # npm run test:unit
  Build:
    runs-on: ubuntu-latest
    needs: Unittest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Lanzar build
        run: |
          set -ev
          cd modern-web-app
          npm ci
          npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: modern-web-app-v${{ github.sha }}
          path: modern-web-app/.next/

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: modern-web-app-${{ github.sha }}
          path: artifact_to_deploy
      - name: Deploy
        run: |
          set -ev
          cd modern-web-app
          npm run deploy     
